In [3]:
import numpy as np
import time

letter = "D"
N = ord(letter) % 15 + 1
print(f"Варіант: {N}")

Варіант: 9


Вправа 1

Постановка задачі: Вводиться число n. Вивести масив розміру n×n, в якому по діагоналі йдуть числа від 1 до n, а інші числа рівні 0.

In [25]:
n = int(input("Введіть n: "))

print("--- NumPy ---")
start = time.perf_counter()
res_np = np.diag(np.arange(1, n + 1))
end = time.perf_counter()
print(f"Час: {end - start:.6f} сек")
print(res_np)

print("\n--- Ітеративний метод ---")
start = time.perf_counter()
res_iter = [[0 for _ in range(n)] for _ in range(n)]
for i in range(n):
    res_iter[i][i] = i + 1
end = time.perf_counter()
print(f"Час: {end - start:.6f} сек")
for row in res_iter:
    print(row)

Введіть n:  50


--- NumPy ---
Час: 0.000086 сек
[[ 1  0  0 ...  0  0  0]
 [ 0  2  0 ...  0  0  0]
 [ 0  0  3 ...  0  0  0]
 ...
 [ 0  0  0 ... 48  0  0]
 [ 0  0  0 ...  0 49  0]
 [ 0  0  0 ...  0  0 50]]

--- Ітеративний метод ---
Час: 0.000275 сек
[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0,

Вправа 2

Постановка задачі: Вводиться число n. Розставити 1 та 0 у шаховому порядку, починаючи з 1 в матриці розміром n×n, використовуючи слайсінг .

In [26]:
n = int(input("Введіть n: "))

print("--- NumPy ---")
start = time.perf_counter()
a = np.zeros((n, n), dtype=int)
a[::2, ::2] = 1
a[1::2, 1::2] = 1
end = time.perf_counter()
print(f"Час: {end - start:.6f} сек")
print(a)

print("\n--- Ітеративний метод ---")
start = time.perf_counter()
res_iter = [[0]*n for _ in range(n)]
for i in range(n):
    for j in range(n):
        if (i + j) % 2 == 0:
            res_iter[i][j] = 1
end = time.perf_counter()
print(f"Час: {end - start:.6f} сек")
for row in res_iter:
    print(row)

Введіть n:  50


--- NumPy ---
Час: 0.000121 сек
[[1 0 1 ... 0 1 0]
 [0 1 0 ... 1 0 1]
 [1 0 1 ... 0 1 0]
 ...
 [0 1 0 ... 1 0 1]
 [1 0 1 ... 0 1 0]
 [0 1 0 ... 1 0 1]]

--- Ітеративний метод ---
Час: 0.000426 сек
[1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,

Вправа 4

Постановка задачі: Вводяться числа n і m. Вивести масив розміру n×m, в якому у першому рядку (індекс 0) йдуть числа від 0 до m−1, а всі інші елементи дорівнюють 0.

In [27]:
n = int(input("Введіть n (рядки): "))
m = int(input("Введіть m (стовпці): "))

print("--- NumPy ---")
start = time.perf_counter()
a = np.zeros((n, m), dtype=int)
a[0, :] = np.arange(m)
end = time.perf_counter()
print(f"Час: {end - start:.6f} сек")
print(a)

print("\n--- Ітеративний метод ---")
start = time.perf_counter()
res_iter = [[0]*m for _ in range(n)]
for j in range(m):
    res_iter[0][j] = j
end = time.perf_counter()
print(f"Час: {end - start:.6f} сек")
for row in res_iter:
    print(row)

Введіть n (рядки):  50
Введіть m (стовпці):  50


--- NumPy ---
Час: 0.000089 сек
[[ 0  1  2 ... 47 48 49]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]

--- Ітеративний метод ---
Час: 0.000098 сек
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

Вправа 7

Постановка задачі: З клавіатури вводиться масив. Замінити всі нульові елементи на -1.

In [29]:
print("Введіть елементи масиву через пробіл:")
raw_input = list(map(int, input().split()))

print("--- NumPy ---")
arr = np.array(raw_input)
start = time.perf_counter()
res_np = np.where(arr == 0, -1, arr)
end = time.perf_counter()
print(f"Час: {end - start:.6f} сек")
print(res_np)

print("\n--- Ітеративний метод ---")
start = time.perf_counter()
res_iter = []
for x in raw_input:
    if x == 0:
        res_iter.append(-1)
    else:
        res_iter.append(x)
end = time.perf_counter()
print(f"Час: {end - start:.6f} сек")
print(res_iter)

Введіть елементи масиву через пробіл:


 12 23 34 0 0 0 56 0 776 87 0


--- NumPy ---
Час: 0.000057 сек
[ 12  23  34  -1  -1  -1  56  -1 776  87  -1]

--- Ітеративний метод ---
Час: 0.000057 сек
[12, 23, 34, -1, -1, -1, 56, -1, 776, 87, -1]


Вправа 8

Постановка задачі: З клавіатури вводиться масив. Підрахувати в ньому кількість нульових та ненульових елементів .

In [32]:
print("Введіть елементи через пробіл:")
raw_input = list(map(int, input().split()))
arr = np.array(raw_input)

print("--- NumPy ---")
start = time.perf_counter()
zeros = np.count_nonzero(arr == 0)
non_zeros = np.count_nonzero(arr != 0)
end = time.perf_counter()
print(f"Час: {end - start:.8f} сек")
print(f"Нулів: {zeros}, Ненульових: {non_zeros}")

print("\n--- Ітеративний метод ---")
start = time.perf_counter()
z_cnt = 0
nz_cnt = 0
for x in raw_input:
    if x == 0:
        z_cnt += 1
    else:
        nz_cnt += 1
end = time.perf_counter()
print(f"Час: {end - start:.8f} сек")
print(f"Нулів: {z_cnt}, Ненульових: {nz_cnt}")

Вправа 8. Введіть елементи через пробіл:


 34 45 4 5 8 7 9 7 7 0 9 8 9 0 9 8 9 0 9 8 90 0 9 0 8 8 9 0 9 0 7 8 7 8 7 8 7 8 9 0 0


--- NumPy ---
Час: 0.00007410 сек
Нулів: 9, Ненульових: 32

--- Ітеративний метод ---
Час: 0.00006230 сек
Нулів: 9, Ненульових: 32


Вправа 12

Постановка задачі: Створити масив одиниць розміром n×n та створити в ньому «рамку», сформовану з 0 (всередині масиву, не змінюючи розмір) .

In [43]:
n = int(input("Введіть n: "))

print("--- NumPy ---")
start = time.perf_counter()
a = np.ones((n, n), dtype=int)
a[0, :] = 0
a[-1, :] = 0
a[:, 0] = 0
a[:, -1] = 0
end = time.perf_counter()
print(f"Час: {end - start:.8f} сек")
print(a)

print("\n--- Ітеративний метод ---")
start = time.perf_counter()
res_iter = [[1]*n for _ in range(n)]
for i in range(n):
    for j in range(n):
        if i == 0 or i == n-1 or j == 0 or j == n-1:
            res_iter[i][j] = 0
end = time.perf_counter()
print(f"Час: {end - start:.8f} сек")

for row in res_iter:
    print(row)

Введіть n:  40


--- NumPy ---
Час: 0.00014380 сек
[[0 0 0 ... 0 0 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 0 0 ... 0 0 0]]

--- Ітеративний метод ---
Час: 0.00032090 сек
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]
[0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]
[0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]
[0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]
[0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]
[0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 

Вправа 15

Постановка задачі: Заповнити парні стовбчики матриці розміром n×n одиницями, а непарні - нулями . (Примітка: в Python нумерація з 0, тому 0-й стовпчик вважаємо парним).

In [44]:
n = int(input("Введіть n: "))

print("--- NumPy ---")
start = time.perf_counter()
a = np.zeros((n, n), dtype=int)
a[:, 1::2] = 1
end = time.perf_counter()
print(f"Час: {end - start:.8f} сек")
print(a)

print("\n--- Ітеративний метод ---")
start = time.perf_counter()
res_iter = [[1]*n for _ in range(n)]
for i in range(n):
    for j in range(n):
        if j % 2 == 0:
            res_iter[i][j] = 0
end = time.perf_counter()
print(f"Час: {end - start:.8f} сек")

for row in res_iter:
    print(row)

Введіть n:  40


--- NumPy ---
Час: 0.00008630 сек
[[0 1 0 ... 1 0 1]
 [0 1 0 ... 1 0 1]
 [0 1 0 ... 1 0 1]
 ...
 [0 1 0 ... 1 0 1]
 [0 1 0 ... 1 0 1]
 [0 1 0 ... 1 0 1]]

--- Ітеративний метод ---
Час: 0.00018360 сек
[0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]
[0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]
[0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]
[0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]
[0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]
[0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]
[0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 

Вправа 16

Постановка задачі: Заповнити вектор значеннями від 0 до n. Всі значення, що більші за n/4 та менші за 3n/4 замінити нулями .

In [46]:
n = int(input("Введіть n: "))

print("--- NumPy ---")
start = time.perf_counter()
arr = np.arange(n + 1)
mask = (arr > n/4) & (arr < 3*n/4)
arr[mask] = 0
end = time.perf_counter()
print(f"Час: {end - start:.8f} сек")
print(arr)

print("\n--- Ітеративний метод ---")
start = time.perf_counter()
res_iter = []
low = n / 4
high = 3 * n / 4
for i in range(n + 1):
    if low < i < high:
        res_iter.append(0)
    else:
        res_iter.append(i)
end = time.perf_counter()
print(f"Час: {end - start:.8f} сек")
print(res_iter)

Введіть n:  40


--- NumPy ---
Час: 0.00011730 сек
[ 0  1  2  3  4  5  6  7  8  9 10  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0 30 31 32 33 34 35 36 37 38 39 40]

--- Ітеративний метод ---
Час: 0.00016440 сек
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40]


Вправа 20

Постановка задачі: Згенерувати вектор із n випадкових елементів, що лежать в інтервалі (0,1). Замінити максимальний елемент на 0.

In [50]:
n = int(input("Введіть n: "))

print("--- NumPy ---")
a = np.random.random(n)
print("Початковий:", np.round(a, 3))

start = time.perf_counter()
idx_max = a.argmax()
a[idx_max] = 0
end = time.perf_counter()
print(f"Час: {end - start:.8f} сек")
print("Змінений:", np.round(a, 3))

print("\n--- Ітеративний метод ---")
lst = np.random.random(n).tolist()
initial_print = [round(x, 3) for x in lst]
print("Початковий:", initial_print)
start = time.perf_counter()
max_val = -1
max_idx = -1
for i in range(len(lst)):
    if lst[i] > max_val:
        max_val = lst[i]
        max_idx = i
if max_idx != -1:
    lst[max_idx] = 0
end = time.perf_counter()
print(f"Час: {end - start:.8f} сек")
res_printed = [round(x, 3) for x in lst]
print("Змінений: ", res_printed)

Введіть n:  10


--- NumPy ---
Початковий: [0.85  0.957 0.522 0.769 0.072 0.91  0.545 0.488 0.567 0.51 ]
Час: 0.00004420 сек
Змінений: [0.85  0.    0.522 0.769 0.072 0.91  0.545 0.488 0.567 0.51 ]

--- Ітеративний метод ---
Початковий: [0.983, 0.975, 0.697, 0.233, 0.71, 0.575, 0.61, 0.784, 0.808, 0.72]
Час: 0.00008530 сек
Змінений:  [0, 0.975, 0.697, 0.233, 0.71, 0.575, 0.61, 0.784, 0.808, 0.72]


Завдання 2. Розв'язання системи рівнянь

Постановка задачі: Розв'язати систему лінійних рівнянь за допомогою формул Крамера, матричного множення (оберненої матриці) та функції numpy.linalg.solve(). Порівняти результати.

In [51]:
A = np.array([
    [1,  2,  1,  1],
    [2,  1,  1,  1],
    [1, -1,  2,  1],
    [1,  1, -1,  3]
])

B = np.array([8, 5, -1, 10])

print("Матриця A:\n", A)
print("Вектор B:", B)
print("-" * 30)

print("1. Метод Крамера:")
det_A = np.linalg.det(A)
print(f"Головний визначник: {det_A:.2f}")

if det_A == 0:
    print("Визначник = 0, метод не працює.")
else:
    x_cramer = []
    for i in range(4):
        Ai = A.copy()
        Ai[:, i] = B
        det_Ai = np.linalg.det(Ai)
        x_cramer.append(det_Ai / det_A)
    
    x_cramer = np.array(x_cramer)
    print(f"Знайдені корені (X): {x_cramer}")

print("\n" + "-" * 30)
print("ПЕРЕВІРКА:")
print("\nа) Матричне множення (A * X):")
check_a = np.dot(A, x_cramer)
print(f"Результат множення: {check_a}")
print(f"Чи дорівнює це вектору B? {np.allclose(check_a, B)}")

print("\nb) Обернена матриця (X = inv(A) * B):")
inv_A = np.linalg.inv(A)
x_inv = np.dot(inv_A, B)
print(f"Корені через обернену матрицю: {x_inv}")

print("\nc) Функція numpy.linalg.solve():")
x_solve = np.linalg.solve(A, B)
print(f"Корені через solve(): {x_solve}")

print("\n" + "-" * 30)
print("Чи всі методи дали однаковий результат?")
match_cramer_inv = np.allclose(x_cramer, x_inv)
match_cramer_solve = np.allclose(x_cramer, x_solve)
print(f"Крамер == Обернена матриця: {match_cramer_inv}")
print(f"Крамер == Solve: {match_cramer_solve}")

Матриця A:
 [[ 1  2  1  1]
 [ 2  1  1  1]
 [ 1 -1  2  1]
 [ 1  1 -1  3]]
Вектор B: [ 8  5 -1 10]
------------------------------
1. Метод Крамера:
Головний визначник: -19.00
Знайдені корені (X): [-0.05263158  2.94736842 -0.15789474  2.31578947]

------------------------------
ПЕРЕВІРКА:

а) Матричне множення (A * X):
Результат множення: [ 8.  5. -1. 10.]
Чи дорівнює це вектору B? True

b) Обернена матриця (X = inv(A) * B):
Корені через обернену матрицю: [-0.05263158  2.94736842 -0.15789474  2.31578947]

c) Функція numpy.linalg.solve():
Корені через solve(): [-0.05263158  2.94736842 -0.15789474  2.31578947]

------------------------------
Чи всі методи дали однаковий результат?
Крамер == Обернена матриця: True
Крамер == Solve: True


Завдання 3. Обчислення матричного виразу

Постановка задачі: Обчислити значення матричного виразу

In [52]:
A = np.array([
    [1, 4, 2],
    [2, 1, -2],
    [0, 1, -1]
])

B = np.array([
    [4, 6, -2],
    [4, 10, 1],
    [2, 4, -5]
])

print("--- NumPy ---")
start = time.perf_counter()

A_sq = np.dot(A, A)

bracket = A_sq + B

term_mult = np.dot(bracket, B)

term_2A = 2 * A

res_np = term_2A - term_mult

end = time.perf_counter()
print(f"Час: {end - start:.8f} сек")
print("Результат:\n", res_np)


print("\n--- Ітеративний метод ---")
def mat_mul(m1, m2):
    r, c, k_len = len(m1), len(m2[0]), len(m2)
    res = [[0]*c for _ in range(r)]
    for i in range(r):
        for j in range(c):
            for k in range(k_len):
                res[i][j] += m1[i][k] * m2[k][j]
    return res

def mat_add(m1, m2):
    return [[m1[i][j] + m2[i][j] for j in range(len(m1[0]))] for i in range(len(m1))]

def mat_sub(m1, m2):
    return [[m1[i][j] - m2[i][j] for j in range(len(m1[0]))] for i in range(len(m1))]

def mat_scale(m, val):
    return [[m[i][j] * val for j in range(len(m[0]))] for i in range(len(m))]

A_lst = A.tolist()
B_lst = B.tolist()

start = time.perf_counter()

A_sq_lst = mat_mul(A_lst, A_lst)

bracket_lst = mat_add(A_sq_lst, B_lst)

term_mult_lst = mat_mul(bracket_lst, B_lst)

term_2A_lst = mat_scale(A_lst, 2)

res_iter = mat_sub(term_2A_lst, term_mult_lst)

end = time.perf_counter()
print(f"Час: {end - start:.8f} сек")

print("Результат:")
for row in res_iter:
    print(row)

--- NumPy ---
Час: 0.00016760 сек
Результат:
 [[ -94 -190  -36]
 [-106 -236   20]
 [ -20  -38  -28]]

--- Ітеративний метод ---
Час: 0.00009680 сек
Результат:
[-94, -190, -36]
[-106, -236, 20]
[-20, -38, -28]
